# Enter any currency of your choice Dollars, Euros, Yen...
TypeWallet: "eur" 

# Enter the number of pages from which to collect data...
NumbersOfCoins: 5

# Path where the file will be saved...
PathToFolder: "/home/onebyteforlife/go/src"
